### ISSUE TITLE
Explantion how to use?

### ISSUE THREAD

**Issue by itay0246** [Hatry1337/csgo-friendcode-sharp#2]
Hello, can you please leave a tutorial how to use or a release, where do i paste my cs friendcode, thanks in advance

**Comment by Hatry1337** [comment]
Hello! You can copy `ByteSwap.cs` and `FriendCode.cs` files right into your project and then use `encode` and `decode` methods of `FriendCode` class like in example program: https://github.com/Hatry1337/csgo-friendcode-sharp/blob/master/CSGOFriendCodeConverter/Program.cs

**Comment by itay0246** [comment]
> Hello! You can copy `ByteSwap.cs` and `FriendCode.cs` files right into your project and then use `encode` and `decode` methods of `FriendCode` class like in example program: https://github.com/Hatry1337/csgo-friendcode-sharp/blob/master/CSGOFriendCodeConverter/Program.cs

thanks for replay! can you show me the code on how to do it i have basic c# knowledge and couldn't figure out how to do it, basically i want to input friendcode which converting to steamid64, thanks
